In [1]:
import pandas as pd
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [2]:
train.head(5)

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [3]:
test.head(5)

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
X = train.drop('label',axis=1).values
y = train["label"]

In [5]:
#Normalize pixel values in range 0-255
X = X/255.0
test_data = test.values/255.0

In [6]:
#reshaping to 28x28 array(batch size, row, col, channel)
X = X.reshape(-1,28,28,1)
test_data = test_data.reshape(-1,28,28,1)

In [8]:
from sklearn.model_selection import train_test_split

X_train,X_val,y_train,y_val = train_test_split(X,y,test_size=0.2)

In [14]:
X_train.shape

(33600, 28, 28, 1)

In [9]:
import torch
from torch import nn

In [10]:
torch.__version__

'2.5.1'

In [11]:
#device agnostic
device= ("cuda" if torch.cuda.is_available() else "cpu")
device

'cpu'

In [13]:
class digit_recognizer(nn.Module):
  def __init__(self,
               input_shape:int,
               hidden_units:int,
               output_shape:int):
      super().__init__()
      self.layer_1 = nn.Sequential(
          nn.Conv2d(in_channels=input_shape,
                    out_channels=hidden_units,
                    kernel_size=3,
                    padding=1,
                    stride=1),
          nn.ReLU(),
          nn.Conv2d(in_channels=hidden_units,
                    out_channels=hidden_units,
                    kernel_size=3,
                    padding=1,
                    stride=1),
          nn.ReLU(),
          nn.MaxPool2d(kernel_size=2,
                      stride=2)
      )
      self.layer_2 = nn.Sequential(
          nn.Conv2d(in_channels=hidden_units,
                    out_channels=hidden_units,
                    kernel_size=3,
                    padding=1,
                    stride=1),
          nn.ReLU(),
          nn.Conv2d(in_channels=hidden_units,
                    out_channels=hidden_units,
                    kernel_size=3,
                    padding=1,
                    stride=1),
          nn.ReLU(),
          nn.MaxPool2d(kernel_size=2,
                      stride=2)
      )
      self.classifier = nn.Sequential(
          nn.Flatten(),
          nn.Linear(in_features=hidden_units,
                   out_features=output_shape)
      )


  def forward(self,x):
      x = self.layer1(x)
      x=self.layer2(x)
      x = self.classifier(x)


      return x

In [17]:
model = digit_recognizer(input_shape=3,
                        hidden_units=10,
                        output_shape=len(X.classes)).to(device)

AttributeError: 'numpy.ndarray' object has no attribute 'classes'